### ISSUE TITLE
Export with content

### ISSUE THREAD

**Issue by VolhaBazhkova** [epam/ai-dial-chat#568]
1. Log in by user1 -> generate any picture using any model (e.g. stable diffusion) -> export the chat
2.  Log in by user2 -> import the chat -> no picture available -> **issue**

**Tasks:**

- [x] Iplement a single export;

- [x] Implement a single import;

- [x] Need to implement loader;
- [x] Need to implement modal for the export type.

![image](https://github.com/epam/ai-dial-chat/assets/111180458/6d907e5a-d769-4cc7-b875-d92dbd5f776f)
![image](https://github.com/epam/ai-dial-chat/assets/111180458/5a57a8a9-4951-436a-9573-c4b8bc727406)

**Expected result:** export with content

**Comment by DaryaKarniyenka** [comment]
Export via the context menu should have two options 
![image](https://github.com/epam/ai-dial-chat/assets/151838896/26dfac5e-a60d-482a-8138-a2657e20d668)
![image](https://github.com/epam/ai-dial-chat/assets/151838896/a610e080-a92f-4f5e-b855-f282d8d7a519)

For global export we should change hint
![image](https://github.com/epam/ai-dial-chat/assets/151838896/5f9b7070-a6d1-4513-87b7-1e0b42ccfbfe)

Loading screen 
![image](https://github.com/epam/ai-dial-chat/assets/151838896/12630133-981f-4ed2-ad76-3ff48e9196d0)

Prototype with animation (press "R" to start animation)
https://www.figma.com/proto/lwL5jneveZczAj5RLcLFH2/DIAL-Chat?page-id=0%3A1&type=design&node-id=5684-9326&viewport=-3751%2C-8437%2C0.28&t=5vVUEIsG53Lnto9W-1&scaling=min-zoom&starting-point-node-id=5684%3A9326&mode=design

**Comment by VolhaBazhkova** [comment]
Reported #651 #652
