### ISSUE TITLE
Need to implement unique folder/chat/prompt names validation and migration

### ISSUE THREAD

**Issue by IlyaBondar** [epam/ai-dial-chat#633]
We want to have unique folder/chat/prompt names on root level or inside parent folder.

What should be done:
- [x] need to rename existing duplication names during **migration to API storage** (add postfix) - done in #265 
- [x] need to add validation during **rename**: unique name in current folder, not allow empty names for chats, prompts, folders
- [x] need to add validation during **drag & drop**: unique name in desctination folder
- [x] not allow to use incorrect symbols in names (`notAllowedSymbols`). Pay attention on case when we autorename chat with first message(need to remove `notAllowedSymbols`, see also #592 ) 
- [x] unique names for replay and playback (add postfix if need - see `getNextDefaultName` method)
- [x] implement folder name limitation - 160 symbols (need to confirm, API storage key has limitation 1024 symbols (starting with entity type prefix i.e. from `/<entity_type>/<bucket>/<path>`)

Additionally:

- [x] generate id for entites(see `getPathToFolderById` + `generateConversationId`) during import and regenerate folderId (see #640 )

**Comment by VolhaBazhkova** [comment]
Verified on UAT server but it's needed to created proper test cases to pass them to Automation team
